export const desserts = [
    {
        "id": 1,
        "title": "Bingsu (빙수)",
        "description": "Bingsu, also known as bingsoo, is a Korean shaved ice dessert with sweet toppings that may include chopped fruit, condensed milk, fruit syrup, and red beans.",
        "image": "./images/desserts/bingsu.jpg",
        "cost": "$9.50",
    },
    {
        "id": 2,
        "title": "Gulab Jamun",
        "description": "Gulab Jamun is a sweet Indian dessert consisting of berry-sized balls made with milk solids, sugar, rose water, and cardamon powder.",
        "image": "./images/desserts/gulabjamun.jpeg",
        "cost": "$7.75",
    },
    {
        "id": 3,
        "title": "Halo-halo",
        "description": "Halo-halo is a shaved ice dessert from the Philipines made with sweetened beans, fruits, jellies, and much more. It is usually topped with milk, flan, ube jam, and ice cream.",
        "image": "./images/desserts/halohalo.jpg",
        "cost": "$9.50",
    },
    {
        "id": 4,
        "title": "Leche Flan",
        "description": "Leche Flan, also known as caramel custard, is a custard dessert with a layer of clear caramel sauce topped with whipped cream and various fruits. It is notoriously popular among many countries, such as Japan, Philippines, and Vietnam.",
        "image": "./images/desserts/lecheflan.jpg",
        "cost": "$5.25",
    },
    {
        "id": 5,
        "title": "Mango Sticky Rice",
        "description": "Mango sticky rice is a traditional Southeast Asian/South Asian dessert made with glutinous rice, fresh mango and coconut milk.",
        "image": "./images/desserts/mangostickyrice.jpg",
        "cost": "$5.50",
    },
    {
        "id": 6,
        "title": "Mochi (もち)",
        "description": "Mochi is a Japanese rice cake made with mochigome (もち米 - a short-grain japonica glutinous rice) and is combined with ingredients such as water, sugar, and cornstarch. It is then stuffed with a sweet filling, such as bean paste or ice cream.",
        "image": "./images/desserts/mochi.jpeg",
        "cost": "$2.00/Mochi",
    },
    {
        "id": 7,
        "title": "Boba Tea",
        "description": "Boba Milk Tea, also known as bubble milk tea, is a tea-based drink from Taiwan. It mostly consists of tea accompanied by chewy tapioca pearls, but it can be made with other toppings as well, such as grass jelly, aloe vera, or red bean. This photo showcases our most popular drink, which is Brown Sugar Milk Tea.",
        "image": "./images/desserts/boba.jpg",
        "cost": "$5.50",
    },
    {
        "id": 8,
        "title": "Iced Coffee",
        "description": "Our iced coffee is made with a dark roast Vietnamese-grown coffee (cà phê sữa đá), served with sugar and sweetened condensed milk.",
        "image": "./images/desserts/cafesuada.jpg",
        "cost": "$3.25",
    },
    {
        "id": 9,
        "title": "Matcha Latte (抹茶)",
        "description": "A matcha latte is a tea latte made with green-tea powder from Japan and steamed milk. This matcha powder is used in place of expresso in a traditional cafe latte, which gives the drink a nice green color with bittersweet, vegetal taste.",
        "image": "./images/desserts/matchalatte.jpg",
        "cost": "$4.25",
    },
]