export const pastries = [
    {
        "id": 1,
        "title": "Curry Beef Triangle",
        "description": "A curry beef triangle, also known as curry puff, is a type of Chinese pastry. It usually has a curry beef filling in the center, with a crispy and flaky shell on the outside.",
        "image": "./images/pastries/currybeeftriangle.jpg",
        "cost": "$2.25/Curry Puff",
    },
    {
        "id": 2,
        "title": "Gunjiya",
        "description": "Gunjiya is a sweet deep-fried dumpling from India made with suji (semolina) or maida (all purpose flour) stuffed with a mixture of sweetened khoa (milk solids) and dried fruits.",
        "image": "./images/pastries/gujiya.jpeg",
        "cost": "$3.00/Gunjiya",
    },
    {
        "id": 3,
        "title": "Egg Bread (계란빵)",
        "description": "Egg bread, or gyeran-ppang, is a warm street snack from South Korea. The fluffy, oblong-shaped loaf of bread is made with whole egg inside the pancake dough, resulting in a sweet and savory flavor.",
        "image": "./images/pastries/gyeranppang.jpeg",
        "cost": "$1.75/Bread Roll",
    },
    {
        "id": 4,
        "title": "Thai Crepe",
        "description": "Thai crepes, also known as Khanom Bueang, is a popular type of street food found in Thailand. These crepes are usually topped/filled with meringue, followed by sweet and salty toppings such as shredded coconut, Foi Thong (strips of fried eggs/egg yolks), and chopped scallions",
        "image": "./images/pastries/khanombueang.jpeg",
        "cost": "$2.50/Crepe",
    },
    {
        "id": 5,
        "title": "Shoutao (壽桃)",
        "description": "A shoutao, also known as longevity peach, is a type of lotus seed bun filled with red bean paste or lotus paste. It is a white with a red dyed tip with a crease along the side, mimicking the shape of a peach.",
        "image": "./images/pastries/longetivitypeach.jpeg",
        "cost": "$3.15/Bun",
    },
    {
        "id": 6,
        "title": "Melon Bread",
        "description": "Melon bread, or melonpan (メロンパン) is a type of sweet bun from Japan with melon flavoring. They are made with an enriched dough covered in a thin layer of crisp cookie dough.",
        "image": "./images/pastries/melonpan.jpg",
        "cost": "$4.50/Bun",
    },
    {
        "id": 7,
        "title": "Bánh Patê Sô",
        "description": "Bánh patê sô, also known as pâté chaud, is a Vietnamese savory puff pastry. This French-inspired pastry is made of a light layered and flaky exterior with a meat filling.",
        "image": "./images/pastries/patechaud.jpeg",
        "cost": "$3.15/Pastry",
    },
    {
        "id": 8,
        "title": "Taiyaki (鯛焼き)",
        "description": "Taiyaki is a Japanese fish-shaped cake, commonly sold as street food. It can go along with various fillings, such as red bean paste, custard, chocolate, cheese, or sweet potato. Taiyaki can also be served with ice cream and various toppings.",
        "image": "./images/pastries/taiyaki.jpeg",
        "cost": "$7.50/Taiyaki",
    },
    {
        "id": 9,
        "title": "Ube Pandesal",
        "description": "Ube pandesal is a type of bread roll in the Philipines with ube flavoring. This sweet purple yam bread roll can be combined with melted cheese for a nice, delicious breakfast.",
        "image": "./images/pastries/ubepandesal.jpeg",
        "cost": "$2.15/Bread Roll",
    },
]